name: currency_cloud
description: A starting point for Dart libraries or applications.
homepage: https://github.com/exitlive/currency-cloud-dart
version: 0.0.5
authors:
  - Daniel Domberger <daniel.domberger@exit.live>
  - Martin Flucka <martin.flucka@exit.live>
environment:
  sdk: '>=1.8.0 <2.0.0'

dependencies:
  http: ^0.11.0
  money: ^0.1.3

dev_dependencies:
  test: ^0.12.0
  mockito: ^0.11.0
