name: currency_cloud
description: A starting point for Dart libraries or applications.
version: 0.0.2
author: Daniel Domberger <daniel.domberger@exitlive.io>

environment:
  sdk: '>=1.0.0 <2.0.0'

dependencies:
  http: ^0.11.0
  money: ^0.1.3

dev_dependencies:
  test: ^0.12.0
  mockito: ^0.11.0
